ISSUE_CATALOG = [
    {
        "key": "pothole",
        "label": "Pothole",
        "group": "Roads",
        "detection_mode": "ai",
        "model_key": "pothole",
        "summary": "Surface collapse, potholes, and deep road cavities.",
    },
    {
        "key": "road_crack",
        "label": "Road Crack",
        "group": "Roads",
        "detection_mode": "ai",
        "model_key": "crack",
        "summary": "Longitudinal or transverse cracks on roads and pavements.",
    },
    {
        "key": "waterlogging",
        "label": "Waterlogging / Flooding",
        "group": "Water & Drainage",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Standing water or flooding that requires scene-level review.",
    },
    {
        "key": "drainage_issue",
        "label": "Drainage Issues",
        "group": "Water & Drainage",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Blocked drains, poor runoff, or overflow around drainage assets.",
    },
    {
        "key": "open_manhole",
        "label": "Open Manholes",
        "group": "Water & Drainage",
        "detection_mode": "ai",
        "model_key": "manhole",
        "summary": "Open or exposed manholes needing fast hazard detection.",
    },
    {
        "key": "garbage_overflow",
        "label": "Garbage Overflow",
        "group": "Sanitation",
        "detection_mode": "ai",
        "model_key": "garbage",
        "summary": "Overflowing bins, spread trash, or visible waste piles.",
    },
    {
        "key": "open_dumping",
        "label": "Open Dumping",
        "group": "Sanitation",
        "detection_mode": "ai",
        "model_key": "garbage",
        "summary": "Unmanaged garbage dumped in open public spaces.",
    },
    {
        "key": "roadside_trash",
        "label": "Roadside Trash",
        "group": "Sanitation",
        "detection_mode": "ai",
        "model_key": "garbage",
        "summary": "Accumulated roadside trash visible from image evidence.",
    },
    {
        "key": "debris_accumulation",
        "label": "Debris Accumulation",
        "group": "Sanitation",
        "detection_mode": "ai",
        "model_key": "garbage",
        "summary": "Construction or roadside debris blocking public space.",
    },
    {
        "key": "traffic_signal_damage",
        "label": "Traffic Signal Damage",
        "group": "Public Assets",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Damaged traffic lights or poles. Good future candidate for a dedicated vision model.",
    },
    {
        "key": "illegal_parking",
        "label": "Illegal Parking",
        "group": "Traffic",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Vehicle obstruction and parking violations need context-aware review.",
    },
    {
        "key": "graffiti_vandalism",
        "label": "Graffiti / Vandalism",
        "group": "Public Assets",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Damage to walls, signs, or public property requiring manual validation.",
    },
    {
        "key": "noise_complaint",
        "label": "Noise Complaints",
        "group": "Environment",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Noise reporting is best handled by metadata or audio workflows, not image AI alone.",
    },
    {
        "key": "air_pollution",
        "label": "Air Pollution Monitoring",
        "group": "Environment",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "Air quality needs sensor or environmental data, not only photo detection.",
    },
    {
        "key": "fallen_wires",
        "label": "Fallen Electric Wires",
        "group": "Safety",
        "detection_mode": "manual",
        "model_key": None,
        "summary": "High-risk incidents are routed directly for manual review and urgent action.",
    },
]


ISSUES_BY_KEY = {issue["key"]: issue for issue in ISSUE_CATALOG}

